name: image_crop_example
description: Demonstrates how to use the image_crop plugin.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  #图片裁剪
  #  image_crop: ^0.3.2
  #拍照相册
  #  image_picker: 0.6.0+10
  image_picker:
    git:
      url: https://github.com/MrLiuYS/plugins.git
      ref: image_picker
  image_crop:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
